"""
Build docs/07_scorecard.md: RT-G vs GYRA Mk1 vs GYRA Mk2 (classical) vs GYRA Mk2 (+ learned control),
from the result files written by the CAD, sizing, simulation and RL scripts.

    python calc/scorecard.py
"""
import json
import math
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def load(p):
    p = os.path.join(ROOT, p)
    return json.load(open(p)) if os.path.exists(p) else {}


mk1 = load("sim/out/summary.json")
size1 = load("calc/out/sizing.json")
mk2 = load("sim/out/mk2_summary.json")
loco = load("rl/runs/loco/eval.json")
nav = load("rl/runs/nav/eval.json")
mp2 = load("cad/out2/mass_properties.json")
xm = load("rl/runs/loco/extra_metrics.json")


def f(x, fmt="{:.1f}", none="—"):
    return none if x is None else fmt.format(x)


# RT-G figures: published (paper/press) or estimated from the paper's mass table with the same
# formulas used for GYRA (calc/sizing.py)
J_rt = 27.6 * 0.4 ** 2 * 0.7 + 160 * 0.4 ** 2
tau_rt = 73.4 * 9.81 * 0.27 * math.sin(math.radians(30))
rt_turn6 = J_rt * 36 / (tau_rt * 0.4)
mk1_spin = mk1.get("spin_total_yaw_deg", 315) / 36.0
L = loco.get("learned", {})
C = loco.get("classical", {})


def radius(res, key="turn_6ms"):
    return None


rows = [
    ("Diameter × width", "800 × 800 mm", "600 × 600 mm", "600 × 700 mm", "600 × 700 mm"),
    ("Mass", "125-160 kg", f"{size1.get('mass_total_kg', 41.4):.1f} kg",
     f"{mp2.get('robot', {}).get('mass', 45.1):.1f} kg", "same"),
    ("Turn in place (mean yaw rate)", "not possible (turns only while rolling)", f"{mk1_spin:.0f}°/s (CMG ratchet)",
     f"{mk2.get('spin3_yaw_rate_dps', 0):.0f}°/s @3 rad/s cmd · {mk2.get('spin6_yaw_rate_dps', 0):.0f}°/s @6",
     f(xm.get("learned", {}).get("spin_mean_dps"), "{:.0f}°/s @3 rad/s cmd")),
    ("Turn radius at 6 m/s", f"~{rt_turn6:.0f} m (lean-precession estimate)",
     f"~{size1.get('turn_radius_m', {}).get('6 m/s', 48):.0f} m (estimate)",
     f"{mk2.get('min_turn_radius_at_6ms_m', 0):.1f} m (0.4 rad/s cmd; falls at 0.6)",
     f(xm.get("learned", {}).get("radius_6ms_m"), "{:.1f} m at 0.6 rad/s cmd, no fall")),
    ("Sensor-pod pitch, 0→3 m/s→0", "≈ pendulum pitch (~40-46°)", f"{mk1.get('drive_peak_spine_pitch_deg', 0.75):.2f}°",
     f"{mk2.get('drive_peak_spine_pitch_deg', 0.39):.2f}°", "same loop"),
    ("Max grade (sim)", "~18° static est., 10° tested", "10°", "14°", "14°"),
    ("Top stable speed", "10 m/s (paper)", f"{size1.get('v_top_ms', 6.4):.1f} m/s (motor)", f"{mk2.get('v_max_ms', 8.5):.1f} m/s", "—"),
    ("Battery", "≈ 2.4 kWh (13S 50 Ah)", "468 Wh", "936 Wh", "936 Wh"),
    ("Lateral shove 300 N @ 3 m/s, peak roll", "—", "—", f"{C.get('push_300N_peak_roll_deg', mk2.get('push_peak_roll_deg', 0)):.1f}°",
     f(L.get("push_300N_peak_roll_deg"), "{:.1f}°")),
]
rc = C.get("random_commands_randomised_dynamics", {})
rl_ = L.get("random_commands_randomised_dynamics", {})
rows += [
    ("Random commands, randomised dynamics + pushes: fall rate", "—", "—", f(rc.get("fall_rate"), "{:.0%}"), f(rl_.get("fall_rate"), "{:.0%}")),
    ("… mean abs speed error", "—", "—", f(rc.get("mean_abs_v_err"), "{:.2f} m/s"), f(rl_.get("mean_abs_v_err"), "{:.2f} m/s")),
    ("… mean abs yaw-rate error", "—", "—", f(rc.get("mean_abs_w_err"), "{:.2f} rad/s"), f(rl_.get("mean_abs_w_err"), "{:.2f} rad/s")),
]
for test, label in (("turn_6ms", "6 m/s turn (0.6 rad/s cmd)"), ("slalom_4ms", "4 m/s slalom (±0.8 rad/s)"),
                    ("speed_steps", "speed steps to 8 m/s")):
    c, l_ = C.get(test, {}), L.get(test, {})
    rows.append((f"{label}: RMS yaw-rate err / max roll / fell", "—", "—",
                 f"{f(c.get('rms_w_err'), '{:.2f}')} / {f(c.get('max_roll_deg'), '{:.0f}°')} / {c.get('fell', '—')}",
                 f"{f(l_.get('rms_w_err'), '{:.2f}')} / {f(l_.get('max_roll_deg'), '{:.0f}°')} / {l_.get('fell', '—')}"))
nb, nl = nav.get("vfh_baseline", {}), nav.get("learned", {})
rows += [
    ("Autonomous nav, 100 random maps: success", "L4 autonomy claimed (no data)", "—", f(nb.get("success_rate"), "{:.0%}") + " (VFH baseline)",
     f(nl.get("success_rate"), "{:.0%}") + " (learned)"),
    ("… collision rate", "—", "—", f(nb.get("collision_rate"), "{:.0%}"), f(nl.get("collision_rate"), "{:.0%}")),
    ("… mean speed on successful runs", "—", "—", f(nb.get("mean_speed_success_ms"), "{:.2f} m/s"), f(nl.get("mean_speed_success_ms"), "{:.2f} m/s")),
]

md = ["# Scorecard: RT-G vs GYRA Mk1 vs GYRA Mk2", "",
      "Generated by `calc/scorecard.py` from the result files. RT-G values are published figures or",
      "estimates from its paper's mass table using the same formulas as GYRA. All GYRA values are simulated.", "",
      "| metric | RT-G / RotunBot | GYRA Mk1 | GYRA Mk2 (classical) | GYRA Mk2 (+ learned) |", "|---|---|---|---|---|"]
md += [f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} |" for r in rows]
open(os.path.join(ROOT, "docs", "07_scorecard.md"), "w").write("\n".join(md) + "\n")
print("\n".join(md))
